# Site settings
author: Dahlia 
title: a cute lil code blog
header-img: img/home-bg.png
email: dahliabloomstone@gmail.com
copyright_name: Dahlia 
description: > # this means to ignore newlines until "baseurl:"
  learning code things
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  DahliaBloomstone

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
